/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.Combate;
import Classes.DefinicoesDeImagem;
import Classes.Inimigo;
import Classes.Personagem;
import Classes.Round;
import java.awt.Color;
import static java.lang.Math.random;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JLabel;
import java.util.Random;
/**
 *
 * @author William
 */
public class BatalhaBoss extends javax.swing.JFrame {
Personagem personagem = new Personagem();
Inimigo inimigo = new Inimigo();
Combate combate = new Combate();
Round round = new Round();
Vitoria vitoria = new Vitoria();
Derrota derrota = new Derrota();
FimJogo fimjogo= new FimJogo();
int roundEspecial;
    /**
     * Creates new form Batalha
     */



    public BatalhaBoss() {
        initComponents();
        defNumRound();
        definirTodasImagens(personagem);
        corBotao();
        setCombate();
        System.out.println("Combate : " + combate.getNum());
       
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Personagem = new javax.swing.JLabel();
        Inimigo = new javax.swing.JLabel();
        VS = new javax.swing.JLabel();
        barVidaPersonagem = new javax.swing.JProgressBar();
        barVidaInimigo = new javax.swing.JProgressBar();
        btnAtaque = new javax.swing.JButton();
        btnDefesa = new javax.swing.JButton();
        btnEspecial = new javax.swing.JButton();
        Dialogue = new javax.swing.JLabel();
        Round = new javax.swing.JLabel();
        numRound = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Personagem.setText("jLabel1");
        getContentPane().add(Personagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 124, 159));

        Inimigo.setText("jLabel1");
        getContentPane().add(Inimigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 110, 159));

        VS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        VS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VS.setText("VS");
        getContentPane().add(VS, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 51, 47));

        barVidaPersonagem.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(barVidaPersonagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 103, -1));

        barVidaInimigo.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(barVidaInimigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 100, -1));

        btnAtaque.setText("Ataque");
        btnAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtaqueActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

        btnDefesa.setText("Defesa");
        btnDefesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefesaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDefesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, -1));

        btnEspecial.setText("Especial");
        btnEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecialActionPerformed(evt);
            }
        });
        getContentPane().add(btnEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, -1));

        Dialogue.setBackground(new java.awt.Color(204, 204, 204));
        Dialogue.setLabelFor(Dialogue);
        Dialogue.setText(" Você acerta o {inimigo.nome} causando {inimigo.vida Antiga - inimigo.Vida }  de dano");
        Dialogue.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(Dialogue, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 272, 470, 113));

        Round.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Round.setText("Round");
        Round.setToolTipText("");
        getContentPane().add(Round, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 24, 50, 20));

        numRound.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numRound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numRound.setText("0");
        getContentPane().add(numRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 50, 20));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Personagem receberPersonagem(Personagem personagem, BatalhaBoss batalha){
        batalha.setVisible(true);
        this.personagem = personagem;
        return personagem;
    }
    
    public void setCombate(){ 
        int t = combate.getNum();
       combate.setNum(t++);
    }

    public Inimigo receberInimigo(Inimigo inimigo){
        this.inimigo = inimigo;
        return inimigo;
    }
    
    public void definirTodasImagens(Personagem personagem){
        DefinicoesDeImagem defImg = new DefinicoesDeImagem();
        Random num = new Random();
        int lvlMonstro, caminhoMonstro;
        float monsterVariation;
        String[] monstros1 = new String[13];
        String[] monstros2 = new String[14];
        String[] monstros3 = new String[10];
        String[][] todosMonstros = new  String[3][14];
        
       
        
        if(personagem.getBatalha() <= 2){
            lvlMonstro = 0;
            monsterVariation = num.nextFloat()*2;
            caminhoMonstro = num.nextInt(11);
            
        }
        else if(personagem.getBatalha() <= 4){
            lvlMonstro = 1;
            monsterVariation = num.nextFloat()*3;
            caminhoMonstro = num.nextInt(13);
        }
        else{
            lvlMonstro = 2;
            monsterVariation = num.nextFloat()*4;
            caminhoMonstro = num.nextInt(9);
        }
        //Setando poder aleatório
        inimigo.setAtk(inimigo.getAtk() + monsterVariation+3);
        inimigo.setDef(inimigo.getDef() + monsterVariation+5);
        inimigo.setVida(inimigo.getVida() + monsterVariation+5);
        
        
       
        
        defImg.escalonarImagem(personagem.getCaminhoImg(), Personagem);
        defImg.escalonarImagem("C:\\RPGame\\src\\Imagens\\boss.png", Inimigo);
        
     

        
        //caminho = "C:\\Users\\William\\Desktop\\IFSP\\2 Semestre\\LP2 - Linguagem de Programação 2\\Programas em Java\\ProjetoLP2\\src\\Imagens\\arenaOriginal.jpg";
        //defImg.escalonarImagem(caminho, Background);
    }
    public void defBarVida(){
        int vidaPersonagem = (int)(personagem.getVida());
        System.out.println("Vida personagem" + vidaPersonagem);
        int vidaInimigo = (int)(inimigo.getVida());
        barVidaPersonagem.setMaximum(vidaPersonagem);
        barVidaInimigo.setMaximum(vidaInimigo);
    }
    
    public void updateBarVida(int vidaPers, int vidaIni){
        barVidaPersonagem.setValue(vidaPers);
        barVidaInimigo.setValue(vidaIni);
    }
    
    public void defNumRound(){
        String txtRound;
        txtRound = Integer.toString(round.getRound());
        numRound.setText(txtRound);
    }
    
    public void updateNumRound(){
        String txtRound;
        round.setRound(round.getRound());
        txtRound = Integer.toString(round.getRound());
        numRound.setText(txtRound);
    }
    
    public void morte(Personagem personagem, Inimigo inimigo){
        
        
        if(personagem.getVida()<= 0){
            Personagem.setVisible(false);
            
            
           derrota.setVisible(true);
          
           dispose();
        }
        else if(inimigo.getVida()<= 0){
            Inimigo.setVisible(false);
            fimjogo.definirTodasImagens(personagem);
            dispose();
            fimjogo.receberPersonagem(personagem, fimjogo);
        } 
        
        
        
    }
        
    
    public void corBotao(){
        if(round.getRound() - roundEspecial <= 3){
            btnEspecial.setBackground(Color.GRAY);
        }
        else{
            btnEspecial.setBackground(Color.WHITE);
        }
    }
    
    private void btnDefesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefesaActionPerformed
       
        combate.lutaDef(personagem, inimigo);
        updateBarVida((int)(personagem.getVida()), (int)(inimigo.getVida()));
        round.setRound(round.getRound()+1);
        morte(personagem, inimigo);
        corBotao();
        updateNumRound();
        
    }//GEN-LAST:event_btnDefesaActionPerformed

    private void btnAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtaqueActionPerformed
        
        combate.lutaAtk(personagem, inimigo);
        updateBarVida((int)(personagem.getVida()), (int)(inimigo.getVida()));
        round.setRound(round.getRound()+1);
        morte(personagem, inimigo);
        corBotao();
        updateNumRound();
    }//GEN-LAST:event_btnAtaqueActionPerformed

    private void btnEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecialActionPerformed
       if(round.getRound() - roundEspecial >= 3){
            combate.lutaEspecial(personagem, inimigo);
            updateBarVida((int)(personagem.getVida()), (int)(inimigo.getVida()));
            round.setRound(round.getRound()+1);
            morte(personagem, inimigo);
            roundEspecial = round.getRound();
            corBotao();
            updateNumRound();
       }
    }//GEN-LAST:event_btnEspecialActionPerformed

    
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatalhaBoss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatalhaBoss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatalhaBoss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatalhaBoss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BatalhaBoss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Dialogue;
    private javax.swing.JLabel Inimigo;
    private javax.swing.JLabel Personagem;
    private javax.swing.JLabel Round;
    private javax.swing.JLabel VS;
    private javax.swing.JProgressBar barVidaInimigo;
    private javax.swing.JProgressBar barVidaPersonagem;
    private javax.swing.JButton btnAtaque;
    private javax.swing.JButton btnDefesa;
    private javax.swing.JButton btnEspecial;
    private javax.swing.JLabel numRound;
    // End of variables declaration//GEN-END:variables
}
